Installer Fix & Gemstone Fix
GridProtectionAlliance/MiMD pull request #16
Opened 2023-09-08 17:12 UTC by prestoncraw

- Updated the paths in Startup.cs to handle the root paths.
- Updated the Page component in MiMD.tsx, with the optional Paths prop to fix the NavLink highlighting issue.
- Added openXDA.APIAuthentication for support of Remote Console
- Added missing dependencies to Installer

2023-09-20 15:54 UTC, clackner-gpa requested changes

2023-09-20 15:54 UTC, clackner-gpa commented on Source/Applications/MiMD/App_Start/UseWhenExtensions.cs
This is `Owin` namespace. Do we really need that file?

2023-09-20 15:54 UTC, clackner-gpa commented on Source/Applications/MiMD/FileParsing/DataOperations/PRC002Operation.cs
> +                            return !fld.Evaluate(activeConfig[fld.Name], fld.PreVal);
since `Evaluate` is a function of `fld` it should have access to `this.PreVal` regardless so you don't have to pass it in from here

2023-09-20 15:54 UTC, clackner-gpa commented on Source/Applications/MiMD/FileParsing/DataOperations/PRC002Operation.cs
> +                                return baseConfigfields.Find(field => field.ID == fld.FieldId).Evaluate(value, PreVal);
`fld` and `baseConfigfields.Find(field => field.ID == fld.FieldId)` are not the same thing so you are taking rule from one and PreVal from another. Is that on purpose?

2023-09-20 15:54 UTC, clackner-gpa commented on Source/Applications/MiMD/FileParsing/DataOperations/PRC002Operation.cs
> +                                    string preval = complianceFieldValueViewTbl.QueryRecordWhere("FieldId = {0}", fld.ID).PreVal;
If `prevVal` comes from `ComplianceFieldValueView` but `Evaluate` comes from `ComplianceField` are they guranteed to use the same `preVal`? This logic conflicts with the one above...

2023-09-20 15:54 UTC, clackner-gpa commented on Source/Applications/MiMD/Model/PRC002/ComplianceField.cs
> +                    return Evaluate(double.Parse(value), PreVal);
To keep it clean I would pares `PreVal` here together with `Value`

2023-09-20 15:54 UTC, clackner-gpa commented on Source/Applications/MiMD/Model/PRC002/ComplianceField.cs
>                  List<double> checks = Value.Split(';').Select(item => double.Parse(item)).ToList();
Assuming this should be `dynamicEvaluatedObject `?

2023-09-20 15:54 UTC, clackner-gpa commented on Source/Applications/MiMD/Model/PRC002/ComplianceField.cs
> +        public bool Evaluate(int value, string PreVal)
```suggestion
        public bool Evaluate(int value, intPreVal)
```

see above. for clarity I would make types match on these

2023-09-20 15:54 UTC, clackner-gpa commented on Source/Applications/MiMD/Model/PRC002/ComplianceField.cs
> +        public override IHttpActionResult Patch([FromBody] ComplianceField record)
I think this will cause issues. What are you saving to the database? The rule will need to save the code not the evaluated version.... otherwhise it won't evaluate properly in the DataOperation

2023-09-20 16:08 UTC, prestoncraw commented on Source/Applications/MiMD/Model/PRC002/ComplianceField.cs
> +        public override IHttpActionResult Patch([FromBody] ComplianceField record)
This will take the value that was passed in from the Endpoint Query and essentially if it was 'PreVal' we evaluate that and save the Value as 'PreVal' if the value wasn't 'PreVal' we just evaluate the value/expression and then save it.

2023-09-20 16:38 UTC, prestoncraw commented on Source/Applications/MiMD/App_Start/UseWhenExtensions.cs
This is for 
`
            app.UseWhen(context => !(context.Request.User is SecurityPrincipal), (branch) =>
            branch.Use<AuthenticationMiddleware>(new AuthenticationOptions()
            {
                SessionToken = "session",
                AuthFailureRedirectResourceExpression = "(?!)",
                AnonymousResourceExpression = "(?!)"
            }));
`. Which lives in `Startup.cs`, at L#141.

2023-09-20 16:52 UTC, prestoncraw commented on Source/Applications/MiMD/FileParsing/DataOperations/PRC002Operation.cs
> +                            return !fld.Evaluate(activeConfig[fld.Name], fld.PreVal);
I changed all methods to only accept value. And now referencing PreVal as this.PreVal.

2023-09-25 16:24 UTC, clackner-gpa commented
This is included in #17

2023-09-25 16:24 UTC, closed without merging