Config Rules & Color Configuration
GridProtectionAlliance/MiMD pull request #17
Opened 2023-09-22 19:12 UTC by prestoncraw

- Added a `ColorConfiguration` component to configure what colors are shown when `LastWriteTime` violates the user set threshold of days. 
- Added a `ConfigFileRules` component to allow a user to configure rules for a specific file pattern. 
- Fixed a couple of UI issues/bugs

2023-09-26 17:29 UTC, clackner-gpa requested changes

2023-09-26 17:29 UTC, clackner-gpa commented on Source/Applications/MiMD/FileParsing/DataOperations/ConfigOperation.cs
> +                foreach (var entry in parsedData)
I would swap this. There are more fields than rules so if you do a `foreach rule in rules` you will cut down time it takes significantly.

2023-09-26 17:29 UTC, clackner-gpa commented on Source/Applications/MiMD/FileParsing/DataOperations/ConfigOperation.cs
> +        private bool EvaluateRule(string CurValue, string Comparison, string RuleValue, string FieldType)
you could pass in the `ConfigFileRules` as a paramter instead on `Comparison`,`RuleValue` and `FieldType`.
Or even better make `Evaluate` part of the `ConfigGieldRule` model.

2023-09-26 17:29 UTC, clackner-gpa commented on Source/Applications/MiMD/FileParsing/DataOperations/ConfigOperation.cs
> +            if (Comparison == "=" && CurValue.Trim() == RuleValue.Trim())
Add the Evaluator piece and the `previousValue` piece like we have in the `PRC002` - you only need to save the `prevValue` to `ConfigRule` and update it there.

2023-09-26 17:29 UTC, clackner-gpa commented on Source/Applications/MiMD/Model/System/ConfigFileRules.cs
> +        [ParentKey(typeof(Meter))]
Ithink you can remove that. It is incorrect

2023-09-26 17:29 UTC, clackner-gpa commented on Source/Applications/MiMD/wwwroot/Scripts/TSX/MiMD/Configuration/ColorConfiguration.tsx
> +                            Title={"Color Picker"}
```suggestion
                            Title={"Edit Configuration Duration"}
```

2023-09-26 17:29 UTC, clackner-gpa commented on Source/Applications/MiMD/wwwroot/Scripts/TSX/MiMD/Configuration/ColorConfiguration.tsx
> +                        <Warning Title={'Delete Color Configuration'}
```suggestion
                        <Warning Title={'Delete Configuration Duration'}
```

2023-09-26 17:29 UTC, clackner-gpa commented on Source/Applications/MiMD/wwwroot/Scripts/TSX/MiMD/Configuration/ColorConfiguration.tsx
> +                            />
No Edit Warning needed

2023-09-26 17:29 UTC, clackner-gpa commented on Source/Applications/MiMD/wwwroot/Scripts/TSX/MiMD/Configuration/ColorConfiguration.tsx
> +                            Message={'This will permanently delete this Color Configuration. Please confirm that this is desired. This action can not be undone.'}
```suggestion
                            Message={'This will permanently delete this Configuration Duration. Please confirm that this is desired. This action can not be undone.'}
```

2023-09-26 17:29 UTC, clackner-gpa commented on Source/Applications/MiMD/wwwroot/Scripts/TSX/MiMD/Configuration/ColorConfiguration.tsx
> +                    <button onClick={addBlankRow} style={{ cursor: 'pointer' }} >
Everything else uses the `Confirmtex={'Add'}` etc for this so we have a blue Add button on the button. try to match that

2023-09-26 17:29 UTC, clackner-gpa commented on Source/Applications/MiMD/wwwroot/Scripts/TSX/MiMD/Configuration/ConfigurationFiles.tsx
> +        return handle;
We are using this across a lot of applications. Make it a `GenericSlice` in the Redux store instead

2023-09-26 17:29 UTC, clackner-gpa commented on Source/Applications/MiMD/wwwroot/Scripts/TSX/MiMD/MiMD.tsx
> +                    <Page Name={"PRC002Change"} Paths={["/Record/:recordID"]}>
does that really have to be an array? That could cause issues.....

2023-09-26 19:36 UTC, prestoncraw commented on Source/Applications/MiMD/wwwroot/Scripts/TSX/MiMD/MiMD.tsx
> +                    <Page Name={"PRC002Change"} Paths={["/Record/:recordID"]}>
When I set this prop up in Gemstone, I made `Paths` an array of strings. However, if this is going to be a problem I can switch to a string || an array of strings.

2023-10-09 15:36 UTC, clackner-gpa approved these changes

2023-10-09 15:37 UTC, clackner-gpa commented on Source/Applications/MiMD/wwwroot/Scripts/TSX/MiMD/MiMD.tsx
> +                    <Page Name={"PRC002Change"} Paths={["/Record/:recordID"]}>
I suspect this causes probelems in other apps but it should be ok if we catch that during the next update

2023-10-09 15:37 UTC, merged