Diagnostic rules Ticket_1166
GridProtectionAlliance/MiMD pull request #21
Opened 2023-10-30 16:30 UTC by prestoncraw

- Added logic for configurable Diagnostic File Alarm Rules along with the UI.
- Fixed bug in DiagnosticByMeter component where you couldn't see the Notes component.
- Made the Meter Label consistent for Diagnostic/Configuration tables.

2023-11-09 18:18 UTC, clackner-gpa requested changes

2023-11-09 18:18 UTC, clackner-gpa commented on Source/Applications/MiMD/wwwroot/Scripts/TSX/MiMD/Configuration/ConfigurationFileRules.tsx
> +                                {showFunctionHelp && <HelperTable Data={help} Title={"Dynamic Expression Examples"} IsOpen={showFunctionHelp} onClose={() => setShowFunctionHelp(!showFunctionHelp)}/>}
Because you already define `isOpen` you can just render the `HelperTable` regardless.

```suggestion
                                <HelperTable Data={help} Title={"Dynamic Expression Examples"} IsOpen={showFunctionHelp} onClose={() => setShowFunctionHelp(!showFunctionHelp)}/>
```

2023-11-09 18:18 UTC, clackner-gpa commented on Source/Applications/MiMD/wwwroot/Scripts/TSX/MiMD/Diagnostic/DiagnosticFileRules.tsx
> +    const regexCheck = (rule: MiMD.IDiagnosticRules) => {
Is this not defined in `gpa-gemstone\helper-functions`? We may want to move it if not

2023-11-09 18:18 UTC, clackner-gpa commented on Source/Applications/MiMD/wwwroot/Scripts/TSX/MiMD/PRC-002/ChangeOverview/ResolveRecord.tsx
> +        {showFunctionHelp && <HelperTable Data={help} Title={"Dynamic Expression Examples"} IsOpen={showFunctionHelp} onClose={() => setShowFunctionHelp(!showFunctionHelp)} />}
```suggestion
        <HelperTable Data={help} Title={"Dynamic Expression Examples"} IsOpen={showFunctionHelp} onClose={() => setShowFunctionHelp(!showFunctionHelp)} />
```

2023-11-09 18:18 UTC, clackner-gpa commented on Source/Applications/MiMD/wwwroot/Scripts/TSX/MiMD/PRC-002/MeterWizzard/ConfigurationfieldEdit.tsx
> +            {showFunctionHelp && <HelperTable Data={help} Title={"Dynamic Expression Examples"} IsOpen={showFunctionHelp} onClose={() => setShowFunctionHelp(!showFunctionHelp)} />}
```suggestion
            <HelperTable Data={help} Title={"Dynamic Expression Examples"} IsOpen={showFunctionHelp} onClose={() => setShowFunctionHelp(false)} />
```

2023-11-09 18:18 UTC, clackner-gpa commented on Source/Applications/MiMD/wwwroot/Scripts/TSX/MiMD/Diagnostic/DiagnosticFileChanges.tsx
> +                            <div className="form-check">
Do we really need `value` and `checked`?

2023-11-09 18:18 UTC, clackner-gpa commented on Source/Applications/MiMD/Controllers/MiMDController.cs
> +        public IHttpActionResult GetAdditionalFieldsForTable(string openXDAParentTable)
Let's talk about this one. We may want to move it into `ModelController`

2023-11-09 18:18 UTC, clackner-gpa commented on Source/Applications/MiMD/FileParsing/DataOperations/AppStatusOperation.cs
> +                        evaluatorVariables["recovery"] = section[1];
Would it make sense to do a general `evaluatorVariables[section[0].ToLower()] = section[1];`?
seeems like we may want to simply add all variables and except for a few specific cases we don't do any transformation

2023-11-09 18:18 UTC, clackner-gpa commented on Source/Applications/MiMD/FileParsing/DataOperations/AppStatusOperation.cs
> +                                catch { } // if exception probably a bad rule..
You should definitely log this tho. I think you can create a static Logger in this file.

2023-11-09 18:18 UTC, clackner-gpa commented on Source/Applications/MiMD/FileParsing/DataOperations/AppStatusOperation.cs
> +                            bool regexCondition = match.Success && rule.ReverseRule || !match.Success && !rule.ReverseRule;
```suggestion
                            bool regexCondition = (match.Success && rule.ReverseRule) || (!match.Success && !rule.ReverseRule);
```

2023-11-09 18:18 UTC, clackner-gpa commented on Source/Applications/MiMD/FileParsing/DataOperations/AppStatusOperation.cs
> +                            else if (sql)
should that be `regexCondition && sql`?

Note that in that case the above would have to make sure we don't create a double trigger

2023-11-09 18:18 UTC, clackner-gpa commented on Source/Applications/MiMD/FileParsing/DataOperations/AppStatusOperation.cs
> +                AppStatusFileChanges record = new AppStatusFileChanges();
Why do we have a `newRecord` and a `record`? Couln't you combine them and just create a `newRecord` as `AppStatusFileChange`?

2023-11-09 18:18 UTC, clackner-gpa commented on Source/Applications/MiMD/FileParsing/DataOperations/AppTraceOperation.cs
> +                List<DiagnosticRecord> records = new List<DiagnosticRecord>();
see `AppStatusFileChange` regarding `newRecord` and `record`

2023-11-09 18:18 UTC, clackner-gpa commented on Source/Applications/MiMD/FileParsing/DataOperations/EmaxEventHisOperation.cs
> +                List<DiagnosticRecord> records = new List<DiagnosticRecord>();
see `AppStatusFileChange` regarding `newRecord` and `record`

2023-11-09 18:18 UTC, clackner-gpa commented on Source/Applications/MiMD/FileParsing/DataOperations/EmaxEventHisOperation.cs
> +                            else if (sql)
see `AppStatusFileChange` regarding `sql` and `regexCondition` logic

2023-11-09 19:19 UTC, prestoncraw commented on Source/Applications/MiMD/wwwroot/Scripts/TSX/MiMD/Diagnostic/DiagnosticFileRules.tsx
> +    const regexCheck = (rule: MiMD.IDiagnosticRules) => {
I don't see one in there but I will open a PR for that..

2023-11-09 19:38 UTC, prestoncraw commented on Source/Applications/MiMD/FileParsing/DataOperations/AppStatusOperation.cs
> +                        evaluatorVariables["recovery"] = section[1];
I think that would make sense, and would also give the user more control over what variables they can use in the rules.

2023-11-10 19:31 UTC, clackner-gpa requested changes

2023-11-10 19:31 UTC, clackner-gpa commented on Source/Applications/MiMD/wwwroot/Scripts/TSX/MiMD/Configuration/ConfigurationByMeter.tsx
> +                return <span className="badge badge-pill badge-warning" style={{ backgroundColor }}>{formattedDate}</span>;
It doesn't matter if all the alarms are also `badge-secondary` since we are overrriding the `backgroundcolor`. If `backgroundColor` is `undefined` React takes that as anot assigned and will use the default (from the `secondary` class in this case

```suggestion
                const formattedDate = moment(item.DateLastChanged).format("MM/DD/YY HH:mm CT");       
                return <span className="badge badge-pill badge-secondary" style={{ backgroundColor: backgroundColor }}>{formattedDate}</span>;
```

2023-11-10 19:31 UTC, clackner-gpa commented on Source/Applications/MiMD/wwwroot/Scripts/TSX/MiMD/Configuration/ConfigurationFileChanges.tsx
> +                                    const backgroundColor = getBackgroundColor(item.LastWriteTime, item.ValidChange, key);
see ConfigurationByMeter

2023-11-10 19:31 UTC, clackner-gpa commented on Source/Applications/MiMD/wwwroot/Scripts/TSX/MiMD/Configuration/ConfigurationFiles.tsx
> +                                const backgroundColor = getBackgroundColor(item.LastWriteTime);
see ConfigurationByMeter

2023-11-10 19:31 UTC, clackner-gpa commented on Source/Applications/MiMD/wwwroot/Scripts/TSX/MiMD/Diagnostic/DiagnosticByMeter.tsx
> +                else backgroundColor = 'none'
```suggestion
                else backgroundColor = undefined
```

2023-11-10 19:31 UTC, clackner-gpa commented on Source/Applications/MiMD/wwwroot/Scripts/TSX/MiMD/Diagnostic/DiagnosticByMeter.tsx
> +                if (backgroundColor !== 'none')
see ConfigurationByMeter

2023-11-10 19:31 UTC, clackner-gpa commented on Source/Applications/MiMD/wwwroot/Scripts/TSX/MiMD/Diagnostic/DiagnosticFiles.tsx
> +                                const backgroundColor = getColor(item.MaxAlarmWriteTime);
see ConfigurationByMeter

2023-11-13 14:51 UTC, clackner-gpa requested changes

2023-11-13 14:51 UTC, clackner-gpa commented on Source/Applications/MiMD/Controllers/MiMDController.cs
>      public class AdditionalFieldValueController : ModelController<AdditionalFieldValue>
Does this need to be a `ModelController`?

2023-11-13 15:03 UTC, prestoncraw commented on Source/Applications/MiMD/Controllers/MiMDController.cs
>      public class AdditionalFieldValueController : ModelController<AdditionalFieldValue>
Well, after searching through the code I couldn't find anywhere that we are even making a call to this endpoint..

2023-11-13 16:30 UTC, clackner-gpa approved these changes

2023-11-13 16:30 UTC, merged