Update gsf
GridProtectionAlliance/MiMD pull request #27
Opened 2024-01-26 20:20 UTC by gcsantos-gpa

2024-01-27 15:30 UTC, clackner-gpa requested changes

2024-01-27 15:30 UTC, clackner-gpa commented on Source/Applications/MiMD/Model/Meter.cs
> +            string whereClause = BuildWhereClause(postData.Searches, new List<object>());
This will cause issues the List handed to `BuildWhereClause` will need to be handed to `RetrieveData` otherwise the SQL Injection Logic won't work properly

2024-01-27 15:30 UTC, clackner-gpa commented on Source/Applications/MiMD/Model/PRC002/ComplianceMeter.cs
> +            string whereClause = BuildWhereClause(postData.Searches, new List<object>());
See `Meter.cs` the same thing applies here and in `UserAccount`

2024-01-29 13:43 UTC, gcsantos-gpa commented on Source/Applications/MiMD/Model/Meter.cs
> +            string whereClause = BuildWhereClause(postData.Searches, new List<object>());
That would mean that GSF is not working either. They contain the following lines...

`
            List<object> param = new();
            ....
            string conditions = BuildWhereClause(postData.Searches, param);
            ...
                if (param.Count() > 0)
                    return connection.RetrieveData(sql, param.ToArray());
                return connection.RetrieveData(sql,"");
`

2024-01-29 15:56 UTC, gcsantos-gpa commented on Source/Applications/MiMD/Model/Meter.cs
>                  return Ok(table);
```suggestion
		DataTable table;
                if (param.Count() > 0)
                    table = connection.RetrieveData(sql, param.ToArray());
		else
			table = connection.RetrieveData(sql, "");

                return Ok(table);
```

2024-01-29 15:57 UTC, gcsantos-gpa commented on Source/Applications/MiMD/Model/Meter.cs
> +            string whereClause = BuildWhereClause(postData.Searches, param);
```suggestion
	    List<object> param = new List<object>();
            string whereClause = BuildWhereClause(postData.Searches, param);
```

2024-01-29 15:58 UTC, gcsantos-gpa commented on Source/Applications/MiMD/Model/Meter.cs
> +            string whereClause = BuildWhereClause(postData.Searches, new List<object>());
Changes made

2024-01-29 16:21 UTC, clackner-gpa approved these changes

2024-01-29 16:21 UTC, merged